;;; Sierra Script 1.0 - (do not remove this comment)
;;; Decompiled by sluicebox
(script# 734)
(include sci.sh)
(use Main)
(use BridgeStrategyPlay)
(use n726)
(use Discard)

(local
	local0
	local1
)

(class Declarer_Third_NT of BridgeStrategyPlay
	(properties)

	(method (think &tmp temp0 temp1 temp2 [temp3 2] temp5 temp6 temp7 temp8 temp9 temp10 temp11)
		(= local1 0)
		(= temp5 (gTrick tricksPlayed:))
		(= theSuitLead (gTrick suitLead:))
		(= temp9 (gTrick highTrump:))
		(= trumps (gTrick trump:))
		(= temp10 (gTrick highOfSuitLead:))
		(self setCurPlyr:)
		(= temp11
			(switch (curPlyr location:)
				(3 global195)
				(4 global196)
				(1 global197)
				(2 global198)
			)
		)
		(cond
			((not (= local1 (curPlyr countSuit: theSuitLead)))
				(cond
					(
						(or
							(== trumps 5)
							(not (curPlyr countSuit: trumps))
							(and
								temp9
								(or
									(not
										(curPlyr
											hasCard: trumps (| temp9 $0f00)
										)
									)
									(== (gTrick highPlayer:) pard)
								)
							)
							(and
								(== (gTrick highPlayer:) pard)
								(not temp9)
								(not
									(LHO hasCard: theSuitLead (| temp10 $0f00))
								)
								(not
									(RHO hasCard: theSuitLead (| temp10 $0f00))
								)
							)
						)
						(= local1 (Discard think:))
						(proc726_0)
					)
					((and temp9 (curPlyr hasCard: trumps (| temp9 $0f00)))
						(= local1 (self overruff: temp9))
					)
					(else
						(= local1 (self bottomCard: trumps))
					)
				)
			)
			(
				(or
					(== local1 1)
					(not
						(curPlyr
							hasCard:
								theSuitLead
								(| (gTrick highOfSuitLead:) $0f00)
						)
					)
				)
				(= local1 (self bottomCard: theSuitLead))
			)
			(else
				(= local1 0)
				(= temp6 (- (+ global434 6) global433))
				(= temp1 (- global433 temp5))
				(= temp7 (- (= temp2 (- 7 global434)) temp1))
				(= temp7 (- (- 7 global434) (- temp5 global433)))
				(self makePlan: 0)
			)
		)
		(if (and (not plan) (not local1))
			(self makePlan: 1)
		)
		(if plan
			(cond
				(local1)
				((== plan 1)
					(= local1 (self checkSplitTops: theSuitLead))
				)
				((and (== plan 31) (== theSuitLead 1))
					(= local1 (self winCheap: 1))
					(self setPlan: 22)
				)
				((and (== plan 32) (== theSuitLead 2))
					(= local1 (self winCheap: 2))
					(self setPlan: 22)
				)
				((and (== plan 33) (== theSuitLead 3))
					(= local1 (self winCheap: 3))
					(self setPlan: 22)
				)
				((and (== plan 34) (== theSuitLead 4))
					(= local1 (self winCheap: 4))
					(self setPlan: 22)
				)
				((and (== plan 2) (== theSuitLead 1))
					(= local1 (self checkSplitTops: 1))
				)
				((and (== plan 3) (== theSuitLead 2))
					(= local1 (self checkSplitTops: 2))
				)
				((and (== plan 4) (== theSuitLead 3))
					(= local1 (self checkSplitTops: 3))
				)
				((and (== plan 5) (== theSuitLead 4))
					(= local1 (self checkSplitTops: 4))
				)
				((and (== plan 6) (== theSuitLead 1))
					(= local1 (self checkSplitTops: 1))
				)
				((and (== plan 7) (== theSuitLead 2))
					(= local1 (self checkSplitTops: 2))
				)
				((and (== plan 8) (== theSuitLead 3))
					(= local1 (self checkSplitTops: 3))
				)
				((and (== plan 9) (== theSuitLead 4))
					(= local1 (self checkSplitTops: 4))
				)
				((and (== plan 10) (== theSuitLead 1))
					(= local1 (self checkFinCard: 1))
				)
				((and (== plan 11) (== theSuitLead 2))
					(= local1 (self checkFinCard: 2))
				)
				((and (== plan 12) (== theSuitLead 3))
					(= local1 (self checkFinCard: 3))
				)
				((and (== plan 13) (== theSuitLead 4))
					(= local1 (self checkFinCard: 4))
				)
				((and (== plan 14) (== theSuitLead 1))
					(= local1 (self checkFinCard: 1))
				)
				((and (== plan 15) (== theSuitLead 2))
					(= local1 (self checkFinCard: 2))
				)
				((and (== plan 16) (== theSuitLead 3))
					(= local1 (self checkFinCard: 3))
				)
				((and (== plan 17) (== theSuitLead 4))
					(= local1 (self checkFinCard: 4))
				)
				((== temp11 2)
					(= local1 (self winCheap: theSuitLead))
				)
			)
		)
		(if
			(and
				(curPlyr countSuit: theSuitLead)
				(or (not (IsObject local1)) (!= (local1 suit:) theSuitLead))
			)
			(= local1 (self checkSplitTops: theSuitLead))
		)
		(if (not local1)
			(= local1 (self checkSplitTops: theSuitLead))
		)
		(self verifiedCard: local1)
	)

	(method (overruff param1 &tmp temp0 temp1 temp2 temp3 temp4)
		(= temp0 20)
		(for ((= temp1 0)) (< temp1 (curPlyr size:)) ((++ temp1))
			(= temp3 (curPlyr at: temp1))
			(if
				(and
					(== (temp3 suit:) trumps)
					(> (temp3 rank:) param1)
					(< (temp3 rank:) temp0)
				)
				(= temp0 (temp3 rank:))
				(= temp4 temp3)
			)
		)
		(return (if (!= temp0 20) temp4 else 0))
	)
)

